#%RAML 1.0 Library
usage: provides library for common types

traits:
  errorResponse: !include traits/errorTrait.raml
  customerHeader: !include traits/customerHeaderTrait.raml
  clientIdEnforce: !include traits/clientidenforce.raml
  authorization: !include traits/authorization-trait.raml
  cwheaders: !include traits/cwheaders.raml