#%RAML 1.0 DataType

properties:             
  userName:
    type: string
    required: true
    description: validate username.
  password:      
    type: string
    required: true
    description: validate password.