#%RAML 1.0 Trait
description: common headers for customer individuals
headers:
  x-request-id: 
   type: string
   required: true
   example: 3fbfa1a7-0533-26d8-a568-b8cb97edc7f3
   description: Unique request identifier
  x-session-id:
    type: string 
    required: true
    example: 3fbfa1a7-0533-26d8-a568-b8cb97edc7f3
    description: Unique request identifier
  