#%RAML 1.0 DataType
properties:
  transactionId:
    description: transactionId of the request that failed
    type: string
    required: false
  errorCode:
    description: errorCode of the request that failed
    type: string
    required: false
  errorMessage:
    description: errorMessage of the request that failed
    type: string
    required: false
  timeStamp:
    description: timestamp at which the error occurred
    type: string
    required: false